[
  ["rpc.ws", "o", {title: "RPC over WebSocket settings"}],
  ["rpc.ws.enable", "b", true, {title: "Enable RPC over WebSocket"}],
  ["rpc.ws.server_address", "s", "", {title: "Cloud server address"}],
  ["rpc.ws.reconnect_timeout_min", "i", 10, {title: "Minimal reconnect timeout"}],
  ["rpc.ws.reconnect_timeout_max", "i", 60, {title: "Maximal reconnect timeout"}],
  ["rpc.ws.ssl_server_name", "s", {title : "TLS Server Name"}],
  ["rpc.ws.ssl_ca_file", "s", {title : "TLS CA file"}],
  ["rpc.ws.ssl_client_cert_file", "s", {title: "TLS client cert file"}],
]
